# This is a basic workflow to help you get started with Actions

name: CI - GitHub Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cn-blog-site-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python Packages
        run: pip install -r requirements.txt
      - name: Run Static Site Generator
        run: python site_generator.py
      - name: Commit generated HTML files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Static Site Generator-created Static HTML Site
     
